version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5431:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###

###> blackfireio/blackfire-symfony-meta ###
  blackfire:
    image: blackfire/blackfire:2
    env_file: .env.local
    environment:
      BLACKFIRE_LOG_LEVEL: 4
    ports: [8307]
###< blackfireio/blackfire-symfony-meta ###
